description "paradox Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env paradoxD_BIN="/usr/bin/paradoxd"
env paradoxD_USER="paradox"
env paradoxD_GROUP="paradox"
env paradoxD_PIDDIR="/var/run/paradoxd"
# upstart can't handle variables constructed with other variables
env paradoxD_PIDFILE="/var/run/paradoxd/paradoxd.pid"
env paradoxD_CONFIGFILE="/etc/paradox/paradox.conf"
env paradoxD_DATADIR="/var/lib/paradoxd"

expect fork

respawn
respawn limit 5 120
kill timeout 600

pre-start script
    # this will catch non-existent config files
    # paradoxd will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$paradoxD_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run paradoxd."
        echo "The setting must appear in $paradoxD_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"paradox Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$paradoxD_PIDDIR"
    chmod 0755 "$paradoxD_PIDDIR"
    chown $paradoxD_USER:$paradoxD_GROUP "$paradoxD_PIDDIR"
    chown $paradoxD_USER:$paradoxD_GROUP "$paradoxD_CONFIGFILE"
    chmod 0660 "$paradoxD_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$paradoxD_PIDFILE" \
    --chuid $paradoxD_USER:$paradoxD_GROUP \
    --exec "$paradoxD_BIN" \
    -- \
    -pid="$paradoxD_PIDFILE" \
    -conf="$paradoxD_CONFIGFILE" \
    -datadir="$paradoxD_DATADIR" \
    -disablewallet \
    -daemon

