#!/usr/bin/env bash
#
#  paradoxd The paradox core server.
#
#
# chkconfig: 345 80 20
# description: paradoxd
# processname: paradoxd
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/paradoxd, see below
if [ -f /etc/sysconfig/paradoxd ]; then
        . /etc/sysconfig/paradoxd
fi

RETVAL=0

prog=paradoxd
# you can override the lockfile via paradoxD_LOCKFILE in /etc/sysconfig/paradoxd
lockfile=${paradoxD_LOCKFILE-/var/lock/subsys/paradoxd}

# paradoxd defaults to /usr/bin/paradoxd, override with paradoxD_BIN
paradoxd=${paradoxD_BIN-/usr/bin/paradoxd}

# paradoxd opts default to -disablewallet, override with paradoxD_OPTS
paradoxd_opts=${paradoxD_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $paradoxd $paradoxd_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
